"""Adjusted relationships between tables

Revision ID: 134b5fc8fb09
Revises: ddf1a33c07f6
Create Date: 2023-08-16 19:07:42.428325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134b5fc8fb09'
down_revision: Union[str, None] = 'ddf1a33c07f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'entries')
    op.drop_column('games', 'participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('participants', sa.VARCHAR(), nullable=True))
    op.add_column('games', sa.Column('entries', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
