"""Adjusted relationships between tables

Revision ID: 26cb6d05fae3
Revises: 134b5fc8fb09
Create Date: 2023-08-16 19:14:04.623895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cb6d05fae3'
down_revision: Union[str, None] = '134b5fc8fb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
