"""Adjusted the game and high score tables to have more useful data

Revision ID: ddf1a33c07f6
Revises: ac9eebba2f38
Create Date: 2023-08-16 18:34:05.684174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf1a33c07f6'
down_revision: Union[str, None] = 'ac9eebba2f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
